version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - BIGQUERY_DATASET=${BIGQUERY_DATASET:-bigquery-public-data.fhir_synthea}
      - VERTEX_MODEL=${VERTEX_MODEL:-gemini-1.5-flash}
      - REGION=${REGION:-us-central1}
    volumes:
      - ./services:/app/services
      - ./main.py:/app/main.py
      - ./config.py:/app/config.py
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    name: healthcare-analytics